-- MySQL Script generated by MySQL Workbench
-- Wed Jun 18 11:13:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `admin_id` INT NOT NULL,
  `admin_hashPassword` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendor` (
  `vendor_id` INT NOT NULL,
  `vendor_hasPassword` VARCHAR(45) NOT NULL,
  `Admin_admin_id` INT NOT NULL,
  PRIMARY KEY (`vendor_id`, `Admin_admin_id`),
  INDEX `fk_Vendor_Admin1_idx` (`Admin_admin_id` ASC)  ,
  CONSTRAINT `fk_Vendor_Admin1`
    FOREIGN KEY (`Admin_admin_id`)
    REFERENCES `mydb`.`Admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `client_id` INT ZEROFILL NOT NULL,
  `Vendor_vendor_id` INT NOT NULL,
  `Admin_admin_id` INT NOT NULL,
  PRIMARY KEY (`client_id`, `Vendor_vendor_id`, `Admin_admin_id`),
  INDEX `fk_Client_Vendor1_idx` (`Vendor_vendor_id` ASC)  ,
  INDEX `fk_Client_Admin1_idx` (`Admin_admin_id` ASC)  ,
  CONSTRAINT `fk_Client_Vendor1`
    FOREIGN KEY (`Vendor_vendor_id`)
    REFERENCES `mydb`.`Vendor` (`vendor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Admin1`
    FOREIGN KEY (`Admin_admin_id`)
    REFERENCES `mydb`.`Admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_cpf` TINYINT(11) NOT NULL,
  `user_email` VARCHAR(155) NOT NULL,
  `Admin_admin_id` INT NOT NULL,
  `Vendor_vendor_id` INT NOT NULL,
  `Client_client_id` INT NOT NULL,
  `Client_Vendor_vendor_id` INT NOT NULL,
  `Client_Admin_admin_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `Admin_admin_id`, `Vendor_vendor_id`, `Client_client_id`, `Client_Vendor_vendor_id`, `Client_Admin_admin_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC)  ,
  UNIQUE INDEX `user_cpf_UNIQUE` (`user_cpf` ASC)  ,
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC)  ,
  INDEX `fk_User_Admin_idx` (`Admin_admin_id` ASC)  ,
  INDEX `fk_User_Vendor1_idx` (`Vendor_vendor_id` ASC)  ,
  INDEX `fk_User_Client1_idx` (`Client_client_id` ASC, `Client_Vendor_vendor_id` ASC, `Client_Admin_admin_id` ASC)  ,
  CONSTRAINT `fk_User_Admin`
    FOREIGN KEY (`Admin_admin_id`)
    REFERENCES `mydb`.`Admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Vendor1`
    FOREIGN KEY (`Vendor_vendor_id`)
    REFERENCES `mydb`.`Vendor` (`vendor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Client1`
    FOREIGN KEY (`Client_client_id` , `Client_Vendor_vendor_id` , `Client_Admin_admin_id`)
    REFERENCES `mydb`.`Client` (`client_id` , `Vendor_vendor_id` , `Admin_admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(45) NOT NULL,
  `event_data` VARCHAR(45) NOT NULL,
  `event_hora` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE INDEX `event_id_UNIQUE` (`event_id` ASC)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `ticket_id` INT NOT NULL,
  `emissao_data` DATE NOT NULL,
  `emissao_hora` VARCHAR(5) NOT NULL,
  `codigo` VARCHAR(64) NOT NULL,
  `Client_client_id` INT NOT NULL,
  `Client_Vendor_vendor_id` INT NOT NULL,
  `Client_Admin_admin_id` INT NOT NULL,
  `Vendor_vendor_id` INT NOT NULL,
  `Vendor_Admin_admin_id` INT NOT NULL,
  `Admin_admin_id` INT NOT NULL,
  `Event_event_id` INT NOT NULL,
  PRIMARY KEY (`ticket_id`, `Client_client_id`, `Client_Vendor_vendor_id`, `Client_Admin_admin_id`, `Vendor_vendor_id`, `Vendor_Admin_admin_id`, `Admin_admin_id`, `Event_event_id`),
  UNIQUE INDEX `ticket_id_UNIQUE` (`ticket_id` ASC)  ,
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC)  ,
  INDEX `fk_Ticket_Client1_idx` (`Client_client_id` ASC, `Client_Vendor_vendor_id` ASC, `Client_Admin_admin_id` ASC)  ,
  INDEX `fk_Ticket_Vendor1_idx` (`Vendor_vendor_id` ASC, `Vendor_Admin_admin_id` ASC)  ,
  INDEX `fk_Ticket_Admin1_idx` (`Admin_admin_id` ASC)  ,
  INDEX `fk_Ticket_Event1_idx` (`Event_event_id` ASC)  ,
  CONSTRAINT `fk_Ticket_Client1`
    FOREIGN KEY (`Client_client_id` , `Client_Vendor_vendor_id` , `Client_Admin_admin_id`)
    REFERENCES `mydb`.`Client` (`client_id` , `Vendor_vendor_id` , `Admin_admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Vendor1`
    FOREIGN KEY (`Vendor_vendor_id` , `Vendor_Admin_admin_id`)
    REFERENCES `mydb`.`Vendor` (`vendor_id` , `Admin_admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Admin1`
    FOREIGN KEY (`Admin_admin_id`)
    REFERENCES `mydb`.`Admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Event1`
    FOREIGN KEY (`Event_event_id`)
    REFERENCES `mydb`.`Event` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Setor` (
  `setor_id` INT NOT NULL AUTO_INCREMENT,
  `setor_nome` VARCHAR(45) NOT NULL,
  `qtde_disponivel` VARCHAR(45) NOT NULL,
  `Event_event_id` INT NOT NULL,
  PRIMARY KEY (`setor_id`, `Event_event_id`),
  UNIQUE INDEX `event_id_UNIQUE` (`setor_id` ASC)  ,
  INDEX `fk_Setor_Event1_idx` (`Event_event_id` ASC)  ,
  CONSTRAINT `fk_Setor_Event1`
    FOREIGN KEY (`Event_event_id`)
    REFERENCES `mydb`.`Event` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cadeira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadeira` (
  `cadeira_id` INT NOT NULL AUTO_INCREMENT,
  `cadeira_status` ENUM('Livre', 'Reservada', 'Ocupada') NOT NULL,
  `Setor_setor_id` INT NOT NULL,
  `Setor_Event_event_id` INT NOT NULL,
  `Ticket_ticket_id` INT NOT NULL,
  `Ticket_Client_client_id` INT NOT NULL,
  `Ticket_Client_Vendor_vendor_id` INT NOT NULL,
  `Ticket_Client_Admin_admin_id` INT NOT NULL,
  `Ticket_Vendor_vendor_id` INT NOT NULL,
  `Ticket_Vendor_Admin_admin_id` INT NOT NULL,
  `Ticket_Admin_admin_id` INT NOT NULL,
  `Ticket_Event_event_id` INT NOT NULL,
  PRIMARY KEY (`cadeira_id`, `Setor_setor_id`, `Setor_Event_event_id`, `Ticket_ticket_id`, `Ticket_Client_client_id`, `Ticket_Client_Vendor_vendor_id`, `Ticket_Client_Admin_admin_id`, `Ticket_Vendor_vendor_id`, `Ticket_Vendor_Admin_admin_id`, `Ticket_Admin_admin_id`, `Ticket_Event_event_id`),
  UNIQUE INDEX `event_id_UNIQUE` (`cadeira_id` ASC)  ,
  INDEX `fk_Cadeira_Setor1_idx` (`Setor_setor_id` ASC, `Setor_Event_event_id` ASC)  ,
  INDEX `fk_Cadeira_Ticket1_idx` (`Ticket_ticket_id` ASC, `Ticket_Client_client_id` ASC, `Ticket_Client_Vendor_vendor_id` ASC, `Ticket_Client_Admin_admin_id` ASC, `Ticket_Vendor_vendor_id` ASC, `Ticket_Vendor_Admin_admin_id` ASC, `Ticket_Admin_admin_id` ASC, `Ticket_Event_event_id` ASC)  ,
  CONSTRAINT `fk_Cadeira_Setor1`
    FOREIGN KEY (`Setor_setor_id` , `Setor_Event_event_id`)
    REFERENCES `mydb`.`Setor` (`setor_id` , `Event_event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cadeira_Ticket1`
    FOREIGN KEY (`Ticket_ticket_id` , `Ticket_Client_client_id` , `Ticket_Client_Vendor_vendor_id` , `Ticket_Client_Admin_admin_id` , `Ticket_Vendor_vendor_id` , `Ticket_Vendor_Admin_admin_id` , `Ticket_Admin_admin_id` , `Ticket_Event_event_id`)
    REFERENCES `mydb`.`Ticket` (`ticket_id` , `Client_client_id` , `Client_Vendor_vendor_id` , `Client_Admin_admin_id` , `Vendor_vendor_id` , `Vendor_Admin_admin_id` , `Admin_admin_id` , `Event_event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
